### PR TITLE
added support for multiple environments

### PR DESCRIPTION
**Pull request by gniquil**
This branch adds support for multiple environments.

@fivetanley My code is not exactly satisfactory as I can't figure out how to automated the testing. More specifically, since this change involves determining which environment ember is running, which needs to be determined in Brocfile, I need to change the Brocfile between tests, which I can't figure out how to do. Let me know if you can give me any pointers.

### CODE REVIEW

**Comment by fivetanley** [comment]
I think we could run multiple test commands in .travis.yml?

**Comment by ascot21** [comment]
This would be :+1:

**Comment by seawatts** [comment]
:+1:

**Comment by seawatts** [comment]
Is there something blocking to get this merged?

**Comment by erickreutz** [comment]
:+1:

**Comment by fivetanley** [comment]
Released in 1.0.0. Thanks!

**Pull request merged**
